core/src/script/CGXP/plugins/FullTextSearch.js
core/src/script/CGXP/widgets/FullTextSearch.js

As for now, the FTS combo is blurred when a map move is detected, for instance when the user has selected a result and made the map center on it.
On the other hand when typing coords in the FTS combo, we want to be able to keep typing until all the digits are provided, even if we type slowly and if the map has been recentered in the meantime.
This PR moves the blurring to the combo's "select" handler, from the mp's "movestart" one.

Blur FTS combo only when selecting a result, not while typing coords

---

core/src/script/CGXP/plugins/Login.js

As for now, the same "loginText" parameter is used to set the text value of both the login tool (in the toolbar) and the submit button (in the login form). If one sets ``loginText: ''`` (for instance to only use an icon in the toolbar), the submit button becomes blank as well.
This PR adds 2 distinct parameters for those buttons, using "loginText" as the default value.

Add parameters to set the login buttons texts independently

---

core/src/script/CGXP/plugins/LayerTree.js

See http://docs.camptocamp.net/cgxp/1.5/lib/plugins/LayerTree.html#config-options

Fix typo in jsdoc of showRestrictedContentWarning

---

core/src/script/CGXP/widgets/tree/LayerTree.js

With this pull request the time slider is put under the layer name if group is configured with time parameters and only one layer is set for this group.
Address the feature: 27.4 - Slider par couche
Please review.

put time slider under layer if alone in group

---

core/src/script/CGXP/plugins/Profile.js

This PR enables the integrator to specify a no data value.
At SITN, our raster *.bt layers have zero as no data value, thus the profiles made on them look like that:
To avoid the vertical lines, we would like to specify a no data value, in order to get that kind of profile:
I hope this is the right solution...
Please review

Add a no data value option to profile plugin

---

core/src/script/CGXP/plugins/Print.js
geoext.ux/ux/SimplePrint/lib/GeoExt.ux/SimplePrint.js

This PR adds the option `ignore` so that certain attributes (with a default value) are hidden in the UI.
{
ptype: "cgxp_print",
...
options: {
...
fieldsExtraClientConfiguration: {
"A4 portrait": {
...
"debug": {
ignore: true
},
...
}
}
},
...
},

Add option to hide print attributes in the UI

---

core/src/script/CGXP/plugins/Profile.js

`Ext.Template.apply` takes a single argument: an array of values.

Fix profile marker label

---

core/src/script/CGXP/widgets/Ext.ux.ColorField.js

Colorpicker (used in drawing tools, fulltextsearch) can't work since the commit https://github.com/camptocamp/cgxp/commit/6a2223803b296bbe99c65d5c3a5b3045582de9c1#diff-39cfd2135c9ca93a86fa9b3f7a91362eR61
That was a board effect after correcting code for jsLint. With my change, the "color picker" works but is the code accepted by JsLint ? I'm not sur to know how to run correctly this specific test

Debug color picker without menu

---

core/src/script/CGXP/plugins/FeaturesWindow.js

The worth case is closed when we open the print panel.
fix #904

Don't remove features when the FeaturesWindow is closed to be able to print them.

---

core/src/script/CGXP/widgets/tree/LayerTree.js

I think that this was injected with commit https://github.com/camptocamp/cgxp/commit/5599b2d7051351bb8659efb770ad185f0fe85fc0
There is now a double `else` section here: https://github.com/camptocamp/cgxp/blob/master/core/src/script/CGXP/widgets/tree/LayerTree.js#L1678-L1688
Please review

Remove double else section

---

core/src/script/CGXP/widgets/RedLiningPanel.js
sandbox/FeatureEditing/ux/widgets/FeatureEditingControler.js

Currently, when a new redlining label is added to the map, the font-size and -family is not explicitly set in the feature style (the font-size will only be set when it's changed in the edit dialog). When this feature is sent in a print request, no font-size and -family is provided, so that the default GeoTools font style will be used for the print, while on the client-side the default OpenLayers/SVG font style was used.
To avoid the discrepancy a default font-size and -family is now set when creating a label feature.
Related to https://github.com/camptocamp/baselstadt_mapbs/issues/31

Set default font-size and -family for redlining labels

---

core/src/script/CGXP/widgets/MapPanel.js

if x and y exist and are null, GeoExt will try to recenter on an invalid center:
x/y > center
https://github.com/geoext/geoext/blob/master/lib/GeoExt/widgets/MapPanel.js#L259
center > recenter
https://github.com/geoext/geoext/blob/master/lib/GeoExt/widgets/MapPanel.js#L361
if x/y are null, center will be created but with NaN values, and the recenter will recenter on I dont know exactly but the end result is a recenter in the middle of the maxExtent.

fix null x/y recenter

---

geoext.ux/ux/WMSBrowser/lib/GeoExt.ux/widgets/tree/WMSBrowserTreePanel.js

Some mapfiles are misconfigured with lowercase srs, exemple:
LAYER
METADATA
"wms_srs" "epsg:21781"
MapServer also return the lowercase srs in getCapabilties response.
This commit permit to load this layers in WMSBrowser.

Compare map srs to uppercase capabilites srs in WMSBrowser

---

core/src/script/CGXP/locale/de.js
core/src/script/CGXP/locale/fr.js
core/src/script/CGXP/plugins/Editing.js
core/src/script/CGXP/widgets/tree/LayerTree.js

Display "Copy to" extra actions in FeatureEditorGrid depending on "copy_to" key/value pair in the layer metadata.
Note that this adds a metadata key/value pair in the layer tree node attributes.

Add "Copy to" functionality to Editing plugin

---

core/examples/print.js
geoext.ux/ux/SimplePrint/lib/GeoExt.ux/SimplePrint.js

With this pull request, the print extent auto fits the map view each time the form panel is displayed.
This is useful in case where the print panel is in an accordion layout and autoFit is set to false.
Currently the print extent fits the map view when the print panel is created. If the user navigates in the map and decides to print it, the print extent may be outside the current view extent. Instead, with this pull request, the print extent auto fits the current map view when the print form is displayed.
I also made it so the print example is zoomed to a more "real" area. It makes the print extent more significant if the map is not zoomed by the user.
Please review.
Replaces #1018.
Fixes #1017

Print autofit

---

core/src/script/CGXP/plugins/Editing.js

With this pull request I fix an issue in editing interface where after cutting a polygon.
This issue happens when for example the layer corresponds to PostGIS table with a MultiPolygon geometry constraint. If the user tries to cut a polygon from this layer to draw a hole in the geometry, the difference service always try to return the simplest geometry as possible. Thus, PostGIS may return a polygon even if the initial geometry is a multipolygon.
When sent back to the client, it may then be impossible to save the cut geometry because of constraints.
With this pull request, the geometry is forced to multi if the original geometry was already multi which means that the constraints on the database will be satisfied.
Please review.

Force geom back from difference service to multi

---

geoext.ux/ux/FeatureEditing/lib/GeoExt.ux/FeatureEditorGrid.js

One need to be careful when changing the geometry of a feature in OpenLayers because it may result in ghost geometries still being displayed on the screen. This is due to the fact that OpenLayers relies on geometries ids to check whether a DOM Element should be re-drawn or not.
Using the same id for the geometry object as @arnaud-morvan did doesn't work in case when the geometry is a multi one.
Instead it's better to remove the feature and re-add it to the layer.
Please review.

Prevent ghost rendering by removing/add feature on undo

---

core/src/script/CGXP/plugins/Editing.js

otherwise this.target is wrong and cause an error.

Add correct scope in ext each loop

---

core/src/script/CGXP/plugins/GetFeature.js

GeoServer uses a lot the namespaces (mapped to workspaces) in WFS.
This makes sure the namespaces a reset between each query (OL discovers the
namespace and sets it in the protocol after the first query).
Something was fixed in OL as well. Hence the OL update.

Fix GetFeature for GeoServer WFS

---

core/src/script/CGXP/plugins/Print.js

The property `checkLegend` of `cgxp.plugins.Print` was ignored, so that the "Show legend" checkbox in the print panel could not be disabled by default.

Fix default value for legend in print panel

---

core/src/script/CGXP/plugins/Editing.js

The Editing plugin was sending the JSON with an XML Content-Type.
Closes #1042.
I was planning to fix OpenLayers instead. Because the protocol could use the format to know what content type it should use, but the format is protocol agnostic and therefore doesn't know a thing about the Content-Type which is HTTP specific. So I've fixed it on CGXP instead.

Correct Content-Type when saving features

---

core/src/script/CGXP/plugins/Editing.js
geoext.ux/ux/FeatureEditing/lib/GeoExt.ux/FeatureEditorGrid.js

The previous commit was disabling the button, but missed the key
shutcuts.

Disable undo key shurtcut when disabled in Editing.

---

core/src/script/CGXP/widgets/tree/LayerTree.js

As for now, the layer id (from the DB) is only available for the layertree leaves (layers with no children) whereas it could be useful for layergroups as well, for instance to open a custom metadata window using this id.
This PR generalizes the "layer_id" attribute for all layertree nodes.

Make a layer id attribute available in all tree nodes

---

core/src/script/CGXP/plugins/Editing.js
core/tests/spec/script/CGXP/plugins/Editing.js

Added a hideWhenNoLayer option to the Editing plugin to make it's
window disapear (instead of being just disabled) when no editable layer
is present.

Can now hide the Editing window when no layer.

---

core/src/script/CGXP/plugins/QueryBuilder.js

Config parameters ``enable_limit_featurecollection`` and ``maxfeatures`` have been removed in GMF 1.6. See how it worked in 1.5:
https://github.com/camptocamp/c2cgeoportal/blob/1.5/c2cgeoportal/views/mapserverproxy.py#L237-L242
As a result it is no longer possible to restrict the number of features returned by a WFS request from the query builder to mapserver (even though it is still possible to set a ``MAXFEATURES`` attribute in ``LAYER``).
This PR adds ``maxFeatures`` in the WFS requests, as it is already done in the GetFeature plugin:
https://github.com/camptocamp/cgxp/blob/master/core/src/script/CGXP/plugins/GetFeature.js#L541

Add maxFeatures param to query builder requests

---

core/src/script/CGXP/widgets/WMSDatePicker.js
core/src/script/CGXP/widgets/tree/LayerTree.js
ext.overrides/ExtOverrides/ExtendIeDetection.js

Force WMSDatePicker layout when using IE to solve the widget not being displayed.
fix https://github.com/camptocamp/cgxp/issues/1056

Add Ext detection for IE11 and greater. 

---

core/src/script/CGXP/plugins/Editing.js

This idea behind this pull request is to avoid possible errors when selecting feature for editing purpose.
This issue was that the polygons are always taken first into account. If a point layer is on top of a polygon one, it's impossible to select the point unless the polygon layer is set to invisible.
This pull request fixes this issue by taking the first result returned by the service which takes into account the visibility order.
The pull request also removes unrequired code. The GetFeature options were not taken into account since we're in a specific case (Editing).
Demo: https://geomapfish-demo.camptocamp.net/pierre/edit

Edit select best feature

---

core/src/script/CGXP/plugins/Editing.js
core/tests/spec/script/CGXP/plugins/Editing.js

Instead of storing the editable layers in an associative array (object) in which the keys are the layers ids, we store them in an array. The advantage is that we keep them in the order as in the tree. We can then query the server for features using the visibility order. Thus the features in the response are ordered as well.
I also simplified the way the menu is created. We may have duplicates if layers are available multiple times in the tree, but I don't think it's a big deal.
Please review.

Take order of layers into account when querying server

---

core/src/script/CGXP/plugins/FullTextSearch.js

The position of the crosshair displayed when feeding the fulltextsearch with coordinates  asks for ``lon``/``lat`` properties in the passed ``position``... which do not exist since ``position`` is a simple coordinates array: https://github.com/camptocamp/cgxp/blob/1.6/core/src/script/CGXP/widgets/FullTextSearch.js#L163

Fix position of FTS showCenter marker

---

core/src/script/CGXP/plugins/GetFeature.js

This was already the case for WFS GetFeature : 
https://github.com/camptocamp/cgxp/blob/3e3ccd6be240e484fb00735d9a652f06be8ef32d/core/src/script/CGXP/plugins/GetFeature.js#L552
We need this in 1.6 for parameter ``floor``.

Add mapPanel params to getFeatureInfo request

---

core/src/script/CGXP/plugins/FeaturesWindow.js
core/src/script/CGXP/plugins/Print.js

printExport() returns an object, not an array (if used with a featureGrid... I do not know what happens with a featureWindow....).
I corrected this for version 2 (instance still using mapfish print 2)
Please review
Replaces https://github.com/camptocamp/cgxp/pull/1079

print plugin - printExport returns an object

---

core/src/script/CGXP/plugins/Editing.js

When editing a layer of points, it is not easy to select an existing one, as the used tolerance is OpenLayers default one (5 pixels).
This PR enables the integrator to specify a larger click tolerance on the map, if needed.
Please review

Add a click tolerance in the editing plugin

---

core/src/script/CGXP/plugins/FullTextSearch.js

Reproducible in https://geomapfish-demo.camptocamp.net/1.6/
* click in the FTS colorpicker > pick a color
* the color picker border becomes red (invalid field content) and a "This field is required" tooltip appears below the standard tooltip.
See 
That's because when selecting a color, the field content is set to "":
https://github.com/camptocamp/cgxp/blob/1.6/core/src/script/CGXP/plugins/FullTextSearch.js#L281
which triggers the default blank content detection.
This PR makes sure the detection is skipped.
By the way in Firefox when clicking on the colorpicker, a text editing cursor appears in the field (not in Chrome). See:
I have not found out yet how to prevent this. Anyone has a tip?

Allow empty content in FTS colorpicker

---

core/src/script/CGXP/plugins/Profile.js

Allow to pass custom options to dygraph in profile tool.

Add dygraphOptions to profile plugin

---

core/src/script/CGXP/plugins/Profile.js

Need this to get labels on separated lines with "\n", because I have very long label with 4 rasters.

Add plugin profile option markerLabelSeparator

---

core/src/script/CGXP/widgets/tree/LayerTree.js

But qgis-server accept also LAYER, and if both LAYER and LAYERS exists, data is rendered twice.
issue reported in https://jira.camptocamp.com/browse/GEO-614

Only LAYERS is valid in wms spec. 

---

core/src/script/CGXP/plugins/QueryBuilder.js

I merge that into 1.6 or into master ?
Fix: #1124
**tmp** demo: https://testgmf.sig.cloud.camptocamp.net/bge/theme/Transport

Fix 'like' filters with special characteres

---

core/src/script/CGXP/plugins/QueryBuilder.js

Fix: #1126
Fix also: GEO-619
Now we are able to query something like `Malval "test"`.

Escape double quotes in query builder

---

core/src/script/CGXP/plugins/Login.js

The current syntax used in the Login plugin to read the response from the server after changing a password causes a JS error:
```
Login.js:601 Uncaught TypeError: Cannot read property 'json' of undefined
```
preventing the confirmation message from being displayed.
The PR fixes the error, by the way using a syntax already used at https://github.com/camptocamp/cgxp/blob/master/core/src/script/CGXP/plugins/Profile.js#L377
Question: do we need to add
```
@include OpenLayers/Format/JSON.js
```
at the top of the Login plugin? There is no such include in the Profile plugin.

Fix syntax used to read a JSON response

---

core/src/doc/requirements

Fix: https://jira.camptocamp.com/browse/GEO-1120 (doc 1.6 is not available)
Because jstools  has change to use python3
Must be ported to master too !

Use jstool 0.6 in cgxp

---

.travis.yml

I think the default notification settings (email to committer) should be sufficient, please merge if you agree.

Remove notifications to mailing list
