- .gitmodules
to fix camptocamp/c2cgeoportal#944 on 1.5
> Cherry pick OpenLayers commit to fix mobile on Android

- core/src/script/CGXP/locale/de.js
- core/src/script/CGXP/locale/fr.js
- core/src/script/CGXP/plugins/Editing.js
See https://github.com/camptocamp/c2cgeoportal/pull/1200
> Handle geometry validation errors in UI

- core/src/script/CGXP/api/Map.js
this function will allow to recenter based on the 4 coords of a bounding box inside the geomapfish api
> Added function recenterOnBoundingBox on Map.js

- CHANGELOG.rst
- core/src/script/CGXP/locale/de.js
- core/src/script/CGXP/locale/fr.js
- core/src/script/CGXP/plugins/FeaturesGrid.js
- core/src/script/CGXP/plugins/Print.js
- geoext.ux/ux/SimplePrint/lib/GeoExt.ux/SimplePrint.js
- geoext.ux/ux/SimplePrint/lib/locale/SimplePrint-de.js
- geoext.ux/ux/SimplePrint/lib/locale/SimplePrint-fr.js
Related to https://github.com/geoext/geoext/pull/105
> Add MapFishPrint V3 support

- core/src/script/CGXP/plugins/WFSPermalink.js
This PR enables to pass a parameter which will make the plugin only recenter the map on the selected features:
See demo:
* Without the parameter (default behavior):http://sitn.ne.ch/dev_internet/wsgi/theme/main?wfs_layer=parcelles&wfs_idemai=17_1599
* With the `wfs_show` parameter: http://sitn.ne.ch/dev_internet/wsgi/theme/main?wfs_layer=parcelles&wfs_idemai=17_1599&wfs_showFeatures=false
Please review
> WFSPermanlink - Add an option to only recenter on features

- core/src/script/CGXP/plugins/Editing.js
> Be able to add some parameters to metadata requests

- core/src/script/CGXP/plugins/ContextualData.js
- core/src/script/CGXP/plugins/Editing.js
- core/src/script/CGXP/plugins/FeaturesGrid.js
- core/src/script/CGXP/plugins/FullTextSearch.js
- core/src/script/CGXP/plugins/GetFeature.js
- core/src/script/CGXP/plugins/GoogleEarthView.js
- core/src/script/CGXP/plugins/LayerTree.js
- core/src/script/CGXP/plugins/Login.js
- core/src/script/CGXP/plugins/Permalink.js
- core/src/script/CGXP/plugins/Print.js
- core/src/script/CGXP/plugins/QueryBuilder.js
- core/src/script/CGXP/plugins/Routing.js
- core/src/script/CGXP/plugins/WFSPermalink.js
Related to https://github.com/camptocamp/c2cgeoportal/pull/1335
> Be able to regenerated a new password

- core/examples/layertree.html
- core/examples/layertree.js
- core/examples/themes.js
- core/src/script/CGXP/locale/de.js
- core/src/script/CGXP/locale/fr.js
- core/src/script/CGXP/tools/tools.js
- core/src/script/CGXP/widgets/WMSDatePicker.js
- core/src/script/CGXP/widgets/slider/WMSTimeSlider.js
- core/src/script/CGXP/widgets/tree/LayerTree.js
Works with time mode ``single`` (a single datepicker is shown) and ``range`` (two synchronized datepickers are shown to select a range).
> Add a WMSDatePicker widget

- core/src/script/CGXP/plugins/FeaturesGrid.js
Don't forget the first element of each array of the concatenate_tabs
object.
> featureGrid - Debug concatenate_tabs

- core/src/script/CGXP/plugins/Redlining.js
> Fix Jshint issue

- core/src/script/CGXP/locale/fr.js
- core/src/script/CGXP/plugins/Profile.js
> Fix i18n of raster layer in the profile

- core/src/script/CGXP/plugins/ContextualData.js
The issue with elevation_dtm/elevation_dsm is that they don't exists
if we don't an mnt AND an mns...
> Use mnt_value/mns_value instance of elevation_dtm/elevation_dsm

- geoext.ux/ux/SimplePrint/lib/GeoExt.ux/SimplePrint.js
Depends on:
https://github.com/geoext/geoext/pull/109 and https://github.com/mapfish/mapfish-print/pull/239
> Fix the job position

- geoext.ux/ux/SimplePrint/lib/GeoExt.ux/SimplePrint.js
- Shows a loading spinner during the print process.
- Directly starts the download once the job is finished.
-  ~~Fixes visual glitches (The panel showing the progress is cleared when a new job is started.).~~ (Apparently the "visual glitches" are the expected behavior.)
> Slightly improve usability issues with print

- core/src/script/CGXP/widgets/tree/LayerTree.js
> Test inrange on add WMTS layers

- core/src/script/CGXP/plugins/Login.js
> Be able to press enter again

- core/src/script/CGXP/widgets/tree/LayerTree.js
> Catch restrictd content on unchanged theme's groups

- CHANGELOG.rst
- core/src/script/CGXP/plugins/Print.js
- geoext.ux/ux/SimplePrint/lib/GeoExt.ux/SimplePrint.js
> Some fix for the print v2

- core/src/theme/all.css
- geoext.ux/ux/SimplePrint/lib/GeoExt.ux/SimplePrint.js
- geoext.ux/ux/SimplePrint/lib/locale/SimplePrint-de.js
- geoext.ux/ux/SimplePrint/lib/locale/SimplePrint-fr.js
Available here: http://geomapfish-demo.camptocamp.net/sbrunner/theme/Transport
> Update the print for the new status responce

- geoext.ux/ux/SimplePrint/lib/GeoExt.ux/SimplePrint.js
> Fix frame not deleted

- core/src/script/CGXP/plugins/FeaturesGrid.js
> add possibility to set the default column width for grids 

- core/src/script/CGXP/plugins/Editing.js
> Adding allowDrag option to prevent users from draging features

- geoext.ux/ux/SimplePrint/lib/locale/SimplePrint-de.js
> Add translation in SimplePrint-de.js

- geoext.ux/ux/FeatureEditing/examples/feature-editor-grid.js
- geoext.ux/ux/FeatureEditing/lib/GeoExt.ux/FeatureEditorGrid.js
This allows users to provide extra items in the actions menu
> Adding extraActions option to featureEditorGrid

- core/src/script/CGXP/plugins/Print.js
- core/src/script/CGXP/plugins/QueryBuilder.js
> url_role_params was replaced by version_role_param in 1.6.0

- core/src/script/CGXP/widgets/FullTextSearch.js
fix camptocamp/baselstadt_mapbs#35
> Fix search result after panning the map

- core/src/script/CGXP/plugins/FullTextSearch.js
Title says it all
PR goes into branch 1.6
Please review
> Remove unneeded comma in FTS

- geoext.ux/ux/SimplePrint/lib/GeoExt.ux/SimplePrint.js
> re-order print buttons

- core/src/script/CGXP/plugins/Editing.js
> Fix copying of features between layers

- core/src/script/CGXP/plugins/WFSPermalink.js
- geoext.ux/ux/FeatureEditing/lib/GeoExt.ux/FeatureEditorGrid.js
> Fix the pointRecenterZoom on WFSPermalink

- core/src/script/CGXP/loader.js
- core/src/script/CGXP/plugins/FloorSlider.js
- core/src/script/CGXP/widgets/FloorSlider.js
- core/tests/SpecRunner.html
- core/tests/spec/script/CGXP/widgets/FloorSlider.js
Added an optional config entry "floors" that can get the list of floors to
show.
> The FloorSlider can now have custom values.

- core/src/script/CGXP/plugins/QueryBuilder.js
> Show drawing layer again in query builder when expanding

- core/src/script/CGXP/plugins/Editing.js
Added two parameters that are true by default:
- enableCutWizard
- enableUndo
> Allow undo and cutWizard to be disabled in Editing

- core/src/script/CGXP/widgets/FloorSlider.js
- core/src/script/CGXP/widgets/MapPanel.js
And removed a global variable.
> Fix permalink for FloorSlider.

- core/src/script/CGXP/plugins/Profile.js
To work with other noDataValue than `0`
See https://github.com/camptocamp/cgxp/pull/951#issuecomment-160554011 for history
> Fix noDataValue option in profile

- core/src/script/CGXP/plugins/FeaturesGrid.js
Mapserver don't seem to garentie the features order
Partially fix #1049
> Partially fix features order

- core/src/script/CGXP/plugins/Menu.js
fix: https://github.com/camptocamp/baselstadt_mapbs/issues/60
> Handle the active action on split button click

- core/src/script/CGXP/locale/fr.js
- core/src/script/CGXP/plugins/Login.js
fix https://github.com/camptocamp/c2cgeoportal/issues/1894
> Add old password field

- core/src/script/CGXP/widgets/tree/LayerTree.js
> Fix timeslider and default expanded groups

- .gitmodules
Change openlayers submodule to camptocamp/openlayer and checkout branch cgxp-1.6 that add one commit.
> Update openlayers to set floor dimension value on WMTS REST layers

- core/src/script/CGXP/widgets/tree/LayerTree.js
fix https://github.com/camptocamp/c2cgeoportal/issues/204
> Fix WMTS dimensions usage

- core/src/script/CGXP/loader.js
- core/src/script/CGXP/plugins/FloorSlider.js
- core/src/script/CGXP/widgets/FloorSlider.js
- core/src/script/CGXP/widgets/MapPanel.js
- core/tests/SpecRunner.html
- core/tests/spec/script/CGXP/widgets/FloorSlider.js
This should have been merged in 1.6 branch.
> Custom values in floor slider

- core/src/script/CGXP/plugins/Editing.js
fixes https://github.com/camptocamp/c2cgeoportal/issues/2090
> Add direct access to editing objects

- core/src/script/CGXP/widgets/tree/LayerTree.js
> Add tree_time_[my_group] permalink support

- core/src/script/CGXP/widgets/tree/LayerTree.js
> Fix fetching of the disclaimer for WMTS layers.

- geoext.ux/ux/SimplePrint/lib/GeoExt.ux/SimplePrint.js
> Don't delete autoCreate from the configuration

- core/src/script/CGXP/widgets/tree/LayerTree.js
> Only one time slider by firstlevel-groups

- core/src/script/CGXP/widgets/FloorSlider.js
Fix for : https://github.com/camptocamp/epfl_authgeoportail/issues/650
> Parse floor that comes from params

- .travis.yml
- core/src/doc/requirements
do it manually and non recursive
> Don't automatically checkout the submodules,

- core/src/script/CGXP/plugins/FeaturesGrid.js
To be able to check some condition to add / remove a button in the 'selection action menu' of the feature grid, It was necessary that I add the possibility to add function on the "On open" (handler) function of the corresponding menu.
With this change, I'm able to run this code: https://github.com/camptocamp/demo_geomapfish/commit/479b2311bf61af72324146c3ad60d748f2104d7a 
(I think that the tests will never more pass...)
> Custom action button

- core/src/script/CGXP/plugins/FeaturesGrid.js
@sbrunner  For 1.6 this time. BS can't upgrade easily to master. (I've done a cherry-pick of the commit (not the merge commit) of https://github.com/camptocamp/cgxp/pull/1114 . Is this alright ?)
> Possibility to add custom action buttons

- core/src/script/CGXP/plugins/Print.js
To use the right DPI parameter
fix https://github.com/camptocamp/ngeo/issues/2793
> Use the right server type on the print

- core/src/script/CGXP/plugins/Print.js
> Fix print of external layers
